/**
 * Populate DB with sample data on server start
 * to disable, edit config/environment/index.js, and set `seedDB: false`
 */

'use strict';

var Thing = require('../api/thing/thing.model');
var User = require('../api/user/user.model');
var Dataview = require('../api/dataView/dataView.model');

Thing.find({}).remove(function() {
  Thing.create({
    name : 'Development Tools',
    info : 'Integration with popular tools such as Bower, Grunt, Karma, Mocha, JSHint, Node Inspector, Livereload, Protractor, Jade, Stylus, Sass, CoffeeScript, and Less.'
  }, {
    name : 'Server and Client integration',
    info : 'Built with a powerful and fun stack: MongoDB, Express, AngularJS, and Node.'
  }, {
    name : 'Smart Build System',
    info : 'Build system ignores `spec` files, allowing you to keep tests alongside code. Automatic injection of scripts and styles into your index.html'
  },  {
    name : 'Modular Structure',
    info : 'Best practice client and server structures allow for more code reusability and maximum scalability'
  },  {
    name : 'Optimized Build',
    info : 'Build process packs up your templates as a single JavaScript payload, minifies your scripts/css/images, and rewrites asset names for caching.'
  },{
    name : 'Deployment Ready',
    info : 'Easily deploy your app to Heroku or Openshift with the heroku and openshift subgenerators'
  });
  });
User.find({}).remove(function() {
  User.create({
    provider: 'local',
    name: 'Test User',
    email: 'test@test.com',
    password: 'test'
  }, {
    provider: 'local',
    role: 'admin',
    name: 'Admin',
    email: 'admin@admin.com',
    password: 'admin'
  }, function() {
      console.log('finished populating users');
    }
  );
  });
Dataview.find({}).remove(function(){
  Dataview.create(
    {
          "AppsName": "@RISK",
          "AppDesc": "@RISK performs risk analysis using Monte Carlo simulation to show many possible outcomes in spreadsheet model. It mathematically and objectively computes and tracks different possible future scenerios",
          "Appversion": "6.0.1",
          "AppDependency": "VIsual C++ 2005Visual C++ 2010Visual C++ 2010 (x64)",
          "AppOwner": "FACULTY",
          "LicenseType": "FBE CONCURRENT",
          "LicenseCount": 30,
          "LicenseUsed": 1,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
   }, {
          "AppsName": "Acrobat Pro",
          "AppDesc": "Acrobat Pro softwareenables user to deliver professional PDF communications. Create and edit PDF files with rich media included, share information.",
          "Appversion": "10.1.1",
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "FBE CONCURRENT",
          "LicenseCount": 60,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
  }, {
          "AppsName": "AcrobatReader",
          "AppDesc": "To view, create, manipulate, print and manage files in Portable Document Format (PDF).",
          "Appversion": 11,
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
  }, {
          "AppsName": "Adobe Captivate",
          "AppDesc": "elearning authoring software for rapidly creating and maintaining interactive eLearning content",
          "Appversion": "CLPE 5. MP Lvl 3 IE (EU)",
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
  }, {
          "AppsName": "Adobe DreamWeaver CS5",
          "AppDesc": "Adobe Dreamweaver (formerly Macromedia Dreamweaver) is a web development application ",
          "Appversion": 11,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 3,
          "LicenseUsed": 3,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
  }, {
          "AppsName": "Adobe Illustrator CS6",
          "AppDesc": "Adobe Illustrator is a vector graphics editor developed and marketed by Adobe Systems. Illustrator is similar in scope, intended market, and functionality to its competitors, CorelDRAW, Xara Designer ",
          "Appversion": "CS6",
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 2,
          "LicenseUsed": 2,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
  }, {
          "AppsName": "Adobe Indesign CS5",
          "AppDesc": "Adobe InDesign is a software application produced by Adobe Systems. It can be used to create works such as posters, flyers, brochures, magazines and books",
          "Appversion": 7,
           "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 6,
          "LicenseUsed": 6,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
  }, {
          "AppsName": "Adobe Photoshop CS5",
          "AppDesc": "Adobe Photoshop is a graphics editing program developed and published by Adobe Systems to alter (a photographic image) digitally using computer software",
          "Appversion": 12,
           "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 8,
          "LicenseUsed": 8,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
  }, {
          "AppsName": "Adobe Photoshop Element",
          "AppDesc": "Adobe Photoshop Elements 9 software is a complete digital photo-editing program. Organize, share, create, and edit photos.",
          "Appversion": 9,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 1,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
  }, {
          "AppsName": "Adobe WebPremium CS4",
          "AppDesc": "Web Premium software provides everything you need to design, develop, and deliver content for multiple devices",
          "Appversion": "CS4",
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 1,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
  }, {
          "AppsName": "Adobe Illustrator CS5",
          "AppDesc": "Create distinctive vector artwork for any project with Adobe Illustrator CS5 graphic design and illustration software",
          "Appversion": 15,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 1,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
  }, {
          "AppsName": "Ami voice",
          "AppDesc": "Transcription software for recognising Japanese conversations.",
          "Appversion": 1,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 0,
          "Department": "Accounting and Corporate Governance",
          "created":1224043200000,
          "AppScope": "STAFF"
  }, {
          "AppsName": "Amos Standalone",
          "AppDesc": "AMOS (Analysis of Moment Structures) is an add-on module for SPSS. It is designed primarily for structural equation modeling, path analysis, and covariance structure modeling",
          "Appversion": 21,
          "AppDependency": "SPSS",
          "AppOwner": "UNI",
          "LicenseType": "UNI SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
  }, {
          "AppsName": "ARC32",
          "AppDesc": "Arc32.exe is one part of Advantage Data Architect developed by iAnywhere Solutions, Inc",
          "Appversion": 1.06,
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "STAT",
          "created":1224043200000,
          "AppScope": "STUDENT"
  }, {
          "AppsName": "Blue Ocean Imulation",
          "AppDesc": "Blue Ocean Strategy Simulation (BOSS) trains participants in strategic thinking and team building. Participants work in teams to manage a fictitious consumer electronics company. The simulation framew",
          "Appversion": "2.2.01",
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "BUSINESS",
          "created":1224043200000,
          "AppScope": "STUDENT"
  }, {
          "AppsName": "Camtasia Studio",
          "AppDesc": "Camtasia Studio and Camtasia for Mac are screen video capture software, published by TechSmith. The user defines the area of the screen or the window that is to be captured or the whole screen can be ",
          "Appversion": 8.3,
          "AppDependency": "MS Office",
          "AppOwner": "FACULTY",
          "LicenseType": "FBE CONCURRENT",
          "LicenseCount": 250,
          "LicenseUsed": 3,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
  }, {
          "AppsName": "Chrome",
          "AppDesc": "open-source web browser",
          "Appversion": 21,
          "AppDependency": "",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STUDENT"
  }, {
          "AppsName": "Citrix Client",
          "AppDesc": "Citrix XenClient enables desktop virtualization",
          "Appversion": "11.0.150",
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
  }, {
          "AppsName": "DataStream",
          "AppDesc": "Thomson Reuters Datastream is the world\'s largest financial statistical database - covering an unrivalled wealth of asset classes, estimates, fundamentals, indices and economic data. You can explore r",
          "Appversion": 5,
          "AppDependency": "MS Office  (Excel X86)",
          "AppOwner": "UNI",
          "LicenseType": "UNI SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "Economics",
          "created":1224043200000,
          "AppScope": "STAFF"
  }, {
          "AppsName": "Dynadock",
          "AppDesc": "Dynadock is a universal docking station with video output to easily connect to all of your workspace peripherals.",
          "Appversion": "2.5.0.5",
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "FACULTY SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
  }, {
          "AppsName": "Ecstat",
          "AppDesc": "Statistical Expert System for Excel.",
          "Appversion": 1,
          "AppDependency": "MS Office",
          "AppOwner": "FACULTY",
          "LicenseType": "FACULTY SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "STAT & ECO",
          "created":1224043200000,
          "AppScope": "STUDENT"
  }, {
          "AppsName": "EndNote",
          "AppDesc": "Software tool for publishing and managing bibliographies",
          "Appversion": "x 4.02",
          "AppDependency": "MS Office",
          "AppOwner": "UNI",
          "LicenseType": "UNI SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "Provided by Library",
          "created":1224043200000,
          "AppScope": "BOTH"
  }, {
          "AppsName": "Eviews-7 -Network",
          "AppDesc": "EViews 7 offers academic researchers, corporations, government agencies, and students access to powerful statistical, forecasting, and modeling tools through an innovative, easy-to-use object-oriented",
          "Appversion": 7.2,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "FBE CONCURRENT",
          "LicenseCount": 200,
          "LicenseUsed": 0,
          "Department": "Economics",
          "created":1224043200000,
          "AppScope": "BOTH"
  }, {
          "AppsName": "Eviews-7 -Standalone",
          "AppDesc": "EViews 7 offers academic researchers, corporations, government agencies, and students access to powerful statistical, forecasting, and modeling tools through an innovative, easy-to-use object-oriented",
          "Appversion": 7.2,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 3,
          "LicenseUsed": 2,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
  }, {
          "AppsName": "Excel Data Analysis Package Add-in",
          "AppDesc": "",
          "Appversion": 2010,
          "AppDependency": "MS Excel",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STUDENT"
  }, {
          "AppsName": "Excel Solver Add-in",
          "AppDesc": "Solver is part of a suite of commands sometimes called what-if analysis tools. With Solver, you can find an optimal value for a formula in one cell — called the target cell — on a worksheet. Solver wo",
          "Appversion": 2010,
          "AppDependency": "MS Excel",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STUDENT"
  }, {
          "AppsName": "Experiment Suite",
          "AppDesc": "Eye tracking software bundle to create, run and analyse eye tracking studies by SMI Sensomotoric Instruments.",
          "Appversion": 1,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 0,
          "Department": "Accounting and Corporate Governance",
          "created":1224043200000,
          "AppScope": "STAFF"
  }, {
          "AppsName": "File Maker Pro",
          "AppDesc": "FileMaker Pro is a database software for Windows",
          "Appversion": 11,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 0,
          "Department": "LNT",
          "created":1224043200000,
          "AppScope": "NO STAFF Linked"
  }, {
          "AppsName": "Firefox",
          "AppDesc": "open-source web browser",
          "Appversion": "17.0.1",
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
  },
      {
          "AppsName": "FlashPlayer",
          "AppDesc": "Adobe® Flash® Player is a cross-platform, browser-based application runtime that provides uncompromised viewing of expressive applications, content, and videos across browsers and operating systems.",
          "Appversion": 11.5,
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "FreeMind",
          "AppDesc": "FreeMind is a free mind mapping application written in Java. FreeMind is licensed under the GNU General Public License. It provides extensive export capabilities. It runs on Microsoft Windows, Linux a",
          "Appversion": "0.8.1",
          "AppDependency": "Java",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Gretl",
          "AppDesc": "Is a cross-platform software package for econometric analysis, written in the C programming language. It is free, open-source software",
          "Appversion": "1.9.11",
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "Grind EQ",
          "AppDesc": "Convert Microsoft Word documents to LaTeX, AMS-LaTeX, TeX, or AMS-TeX format. Converts MathType to Microsoft Equation.",
          "Appversion": 2010,
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 2,
          "LicenseUsed": 2,
          "Department": '',
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Itunes",
          "AppDesc": "iTunes in the Cloud beta lets you automatically download new music, app and book purchases to all your devices",
          "Appversion": "10.4.1",
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Java",
          "AppDesc": "Java software brings interactivity to the Internet, real-time graphics to television, instant imaging to cameras, and multi-player games to mobile phones and desktop PCs.",
          "Appversion": 7.11,
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "JmulTi",
          "AppDesc": "JMulTi is an open-source interactive software for econometric analysis, specialised in univariate and multivariate time series analysis. It has a Java graphical user interface.",
          "Appversion": 4.24,
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "Latec",
          "AppDesc": "",
          "Appversion": 1,
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "FACULTY SITE",
          "LicenseCount": "",
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "LatentGold",
          "AppDesc": "Latent GOLD 4.5 is a powerful latent class and finite mixture program. Latent GOLD contains separate modules for estimating three different model structures -- LC Cluster models, DFactor models, and L",
          "Appversion": 4.5,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 0,
          "Department": "BUSINESS",
          "created":1224043200000,
          "AppScope": "NO STAFF Linked"
      }, {
          "AppsName": "Leximancer",
          "AppDesc": "Specialist Analytics technology for unstructured, qualitative, textual data.",
          "Appversion": 3.5,
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "FACULTY SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Limdep",
          "AppDesc": "Estimation of linear and nonlinear regression models and qualitative dependent variable models for cross-section, time-series and panel data.",
          "Appversion": 10,
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 5,
          "LicenseUsed": 2,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Lisrel",
          "AppDesc": "LISREL, an acronym for linear structural relations, is a statistical software package used in structural equation modeling",
          "Appversion": 8.8,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 1,
          "Department": "Economics",
          "created":1224043200000,
          "AppScope": "NO STAFF Linked"
      }, {
          "AppsName": "Maple",
          "AppDesc": "Maple Professional is the flagship of the tree outline managers for power users.It offers all features of Maple, plus several advanced commands of interest to the professional users.",
          "Appversion": 9.5,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 1,
          "Department": "",
          "created":1224043200000,
          "AppScope": "Not Required Now"
      }, {
          "AppsName": "Maple",
          "AppDesc": "Maple is a commercial computer algebra system.Maple is based on a small kernel, written in C, which provides the Maple language. Most functionality is provided by libraries, which come from a variety ",
          "Appversion": 16,
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 3,
          "LicenseUsed": 2,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Mathematica",
          "AppDesc": "Mathematica is a computational software program used in scientific, engineering, and mathematical fields and other areas of technical computing. It was conceived by Stephen Wolfram and is developed by",
          "Appversion": "8.0.1",
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "MathType",
          "AppDesc": "MathType is a powerful interactive equation editor for Windows and Macintosh that lets you create mathematical notation for word processing, web pages, desktop publishing, presentations, elearning, an",
          "Appversion": 6.8,
          "AppDependency": "MS Office",
          "AppOwner": "FACULTY",
          "LicenseType": "FBE CONCURRENT",
          "LicenseCount": 25,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Matlab",
          "AppDesc": "MATLAB (matrix laboratory) is a numerical computing environment and fourth-generation programming language. Developed by MathWorks, MATLAB allows matrix manipulations, plotting of functions and data, ",
          "Appversion": "R2012b",
          "AppDependency": "Visual C++ 2005 (x64)",
          "AppOwner": "FOS",
          "LicenseType": "FBE CONCURRENT",
          "LicenseCount": 100,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "Matlab",
          "AppDesc": "MATLAB (matrix laboratory) is a numerical computing environment and fourth-generation programming language. Developed by MathWorks, MATLAB allows matrix manipulations, plotting of functions and data, ",
          "Appversion": 5.2,
          "AppDependency": "Packageing not Required,Run Off the Network, License Server",
          "AppOwner": "FACULTY",
          "LicenseType": "FBE CONCURRENT",
          "LicenseCount": 50,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Microfit",
          "AppDesc": "An interactive econometric software. Microfit 5.0 is an interactive, menu-driven program with a host of facilities for estimating, hypothesis testing, forecasting, data processing, file management, an",
          "Appversion": 5,
          "AppDependency": "Packageing not Required,Run Off the Network",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 5,
          "LicenseUsed": 2,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Minitab (Network)",
          "AppDesc": "MINITAB is a general purpose, highly interactive statistical computing system designed especially for students and researchers who have little or no previous experience with computers. It on the ACCC ",
          "Appversion": "16.2.1",
          "AppDependency": "Need to upgrade to windows 7 license in License server",
          "AppOwner": "UNI",
          "LicenseType": "UNI SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "Minitab (Standlone)",
          "AppDesc": "MINITAB is a general purpose, highly interactive statistical computing system designed especially for students and researchers who have little or no previous experience with computers. It on the ACCC ",
          "Appversion": 16,
          "AppDependency": "",
          "AppOwner": "UNI",
          "LicenseType": "UNI SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Morae",
          "AppDesc": "Morae is software for usability testing and user experience research that helps you identify site and application design problems and share them",
          "Appversion": 3.2,
          "AppDependency": "web",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 1,
          "Department": "Web Team",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Mplus",
          "AppDesc": "Mplus is a statistical modeling program that provides researchers with a flexible tool to analyze their data. Mplus offers researchers a wide choice of models, estimators, and algorithms in a program ",
          "Appversion": 6.12,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 0,
          "Department": "Economics",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "MQ VPN",
          "AppDesc": "",
          "Appversion": 1,
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "Faculty IN HOUSE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "MS Office 2010",
          "AppDesc": "Microsoft Office 2010 (also called Office 2010 and Office 14) is a productivity suite for Microsoft Windows,and the successor to Microsoft Office 2007. Office 2010 includes extended file format suppor",
          "Appversion": "2010 SP1",
          "AppDependency": "N/A",
          "AppOwner": "UNI",
          "LicenseType": "UNI SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "MS Project 2010",
          "AppDesc": "Microsoft Project (or MSP or WinProj) is a project management software program developed and sold by Microsoft which is designed to assist project managers",
          "Appversion": 2010,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 15,
          "LicenseUsed": 15,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "MS Visio 2010",
          "AppDesc": "Microsoft Visio (formerly known as Microsoft Office Visio), is a commercial diagramming program for Microsoft Windows that uses vector graphics to create diagrams.",
          "Appversion": 2010,
           "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 39,
          "LicenseUsed": 24,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Music 2 Go",
          "AppDesc": "Music2Go is a Principles of Marketing Simulation enabling students to formulate a Sales and Marketing Strategy and run a Marketing Campaign for an MP3",
          "Appversion": 6.67,
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "MYOB",
          "AppDesc": "MYOB are softwares that are used by small businesses and accounting firms to help them generate more profit and lessen the cost of running their businesses",
          "Appversion": 19.6,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "FACULTY SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "Net Logo",
          "AppDesc": "",
          "Appversion": "5.0.3",
          "AppDependency": "",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "Marketing and Management",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "Nvivo",
          "AppDesc": "Qualitative data analysis software, qualitative research, market research",
          "Appversion": 10,
          "AppDependency": "SQL 2008 R2",
          "AppOwner": "UNI",
          "LicenseType": "UNI SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Oxmetrics",
          "AppDesc": "OxMetrics is an econometric software including the Ox programming language for econometrics and statistics",
          "Appversion": 6.3,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 2,
          "LicenseUsed": 2,
          "Department": "Economics",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "PatchLink",
          "AppDesc": "Identify and Patch Software Security Vulnerabilities Quickly with Lumension® Endpoint Management and Security Suite: Patch and Remediation.",
          "Appversion": "7.2.1",
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "FACULTY SITE",
          "LicenseCount": 671,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "PCTeX",
          "AppDesc": "Is a complete TeX and LaTex publishing software. PcTeX provides a typesetting software solution that will enable users to publish documents, formulas, equations, and thoughts in a professional format ",
          "Appversion": 6,
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 2,
          "LicenseUsed": 2,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "PDF Annotator",
          "AppDesc": "PDF Annotator lets the user open any PDF file and add annotations, using the mouse or a Tablet PC pen",
          "Appversion": 3,
          "AppDependency": "Acrobat reader",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 4,
          "LicenseUsed": 3,
          "Department": "Economics",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "QMWin32",
          "AppDesc": "POM-QM is a software for production/operations management, quantitative methods, management science, and operations research. In the new version of the Windows software, POM for Windows, QM for Window",
          "Appversion": 1,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "FACULTY SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "STAT",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "Quickbooks",
          "AppDesc": "QuickBooks is a line of business accounting software developed and marketed by Intuit",
          "Appversion": 19,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "FACULTY SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "Quicktime",
          "AppDesc": "QuickTime is an extensible proprietary multimedia framework developed by Apple Inc., capable of handling various formats of digital video, picture, sound, panoramic images, and interactivity",
          "Appversion": "7.6.9",
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "R for Windows",
          "AppDesc": "R is a system for statistical computation and graphics. It consists of a language plus a run-time environment with graphics, a debugger, access to certain system functions, and the ability to run prog",
          "Appversion": "3.0.1",
          "AppDependency": "None",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "ReadAbility Formulas",
          "AppDesc": "READABILITY FORMULA takes a sample of your writing and calculates the number of sentences, words, syllables, and characters in your sample. READABILITY FORMULA takes the output of these numbers and pl",
          "Appversion": 7.4,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 1,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "RealPlayer",
          "AppDesc": "RealPlayer. It\'s the best free media player available to play, manage and download all your mp3, flash and video files",
          "Appversion": "14.0.7.669",
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "SAGE",
          "AppDesc": "Sage is a computer package that deals with mathematics. It\'s primarily used in Accounting (Accounts, Book-keeping, Payroll etc)but is also used in science based or engineering jobs.Sage\'s integrated b",
          "Appversion": 1,
          "AppDependency": "MS Office",
          "AppOwner": "FACULTY",
          "LicenseType": "Faculty IN HOUSE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "OBSOLETE"
      }, {
          "AppsName": "SAP interface",
          "AppDesc": "SAP-Interface is a non-profit company/organization which provide SAP Interface development tools.Our free software are SAP RFC Pro, SGC Server, MIL-Read Table, MIL-Backup ABAP Program and still many ",
          "Appversion": 7.2,
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "SAS",
          "AppDesc": "SAS is an integrated system of software products provided by SAS Institute Inc. that enables programmers to perform:data entry, retrieval, management, and mining,report writing and graphics,statistica",
          "Appversion": 9.3,
          "AppDependency": "N/A",
          "AppOwner": "UNI",
          "LicenseType": "UNI SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "SawTooth",
          "AppDesc": "Survey software for creating web-based surveys.",
          "Appversion": 7,
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "FACULTY SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Scientific Notebook",
          "AppDesc": "Scientific Notebook Version 5.5 is ideal for reports, homework, and exams. With Scientific Notebook, creating attractive documents that contain text, mathematics, and graphics is seamless and easy.",
          "Appversion": 3.5,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "FBE CONCURRENT",
          "LicenseCount": 41,
          "LicenseUsed": 0,
          "Department": "STAT",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "Scientific Workplace",
          "AppDesc": "Scientific WorkPlace is a software package for scientific word processing on Microsoft Windows.",
          "Appversion": 5.5,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 8,
          "LicenseUsed": 7,
          "Department": "Economics",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Scilab",
          "AppDesc": "Scilab is an open source, cross-platform numerical computational package and a high-level, numerically oriented programming language. It can be used for signal processing, statistical analysis, image ",
          "Appversion": 5.4,
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "ShazamP",
          "AppDesc": "SHAZAM is a comprehensive econometrics and statistics package for estimating, testing, simulating and forecasting many types of econometrics and statistical models.",
          "Appversion": "11.0.5",
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "FACULTY SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "Shockwave",
          "AppDesc": "Adobe Shockwave is a multimedia platform used to add animation and interactivity to web pages. It allows Adobe Director applications to be published on the Internet and viewed in a web browser on any ",
          "Appversion": "11.6.8.638",
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "Snagit",
          "AppDesc": "Screenshot capturing software",
          "Appversion": "10.0.1.0",
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 15,
          "LicenseUsed": 3,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Sophos",
          "AppDesc": "Sophos is an Antivirus, Email Spam Protection and Endpoint Management Software for Windows, Mac and Linux",
          "Appversion": 9.5,
          "AppDependency": "N/A",
          "AppOwner": "UNI",
          "LicenseType": "UNI SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "Splus",
          "AppDesc": "S-PLUS is a commercial implementation of the S programming language sold by TIBCO Software Inc.It features object-oriented programming capabilities and advanced analytical algorithms.",
          "Appversion": 8.2,
          "AppDependency": "N/A",
          "AppOwner": "UNI",
          "LicenseType": "UNI SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "SPSS Modeler",
          "AppDesc": "SPSS Modeler is a powerful, versatile data mining workbench that helps to build accurate predictive models quickly and intuitively, without programming",
          "Appversion": 14.2,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "FACULTY SITE",
          "LicenseCount": 1000,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "SPSS Network",
          "AppDesc": "SPSS is a computer program used for survey authoring and deployment (IBM SPSS Data Collection), data mining (IBM SPSS Modeler), text analytics, statistical analysis, and collaboration & deployment (ba",
          "Appversion": 21,
          "AppDependency": "N/A",
          "AppOwner": "UNI",
          "LicenseType": "UNI SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "SPSS Standalone",
          "AppDesc": "SPSS is a computer program used for survey authoring and deployment (IBM SPSS Data Collection), data mining (IBM SPSS Modeler), text analytics, statistical analysis, and collaboration & deployment (ba",
          "Appversion": 20,
          "AppDependency": "N/A",
          "AppOwner": "UNI",
          "LicenseType": "UNI SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Stat Transfer",
          "AppDesc": "Stat Transfer provides a fast way to move your data between SAS and a variety of spreadsheets, databases and other statistical packages.",
          "Appversion": 10,
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "FACULTY SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "STATA SE",
          "AppDesc": "Stata is an environment for manipulating and analyzing data using statistical and graphical methods. Stata is an integrated package.SE means special version.",
          "Appversion": 11,
           "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 27,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "TexFonts25 ",
          "AppDesc": "",
          "Appversion": 1,
          "AppDependency": "Firefox",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "Timetrade",
          "AppDesc": "online appointment scheduling systems  software",
          "Appversion": 1,
          "AppDependency": "",
          "AppOwner": "WEB APP",
          "LicenseType": "WEB APP",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Vensim",
          "AppDesc": "Vensim is a simulation software made by Ventana Systems, Inc. (Harvard, Massachusetts). Its purpose is to help companies to find an optimal solution for various situations that need analysis and where",
          "Appversion": "5.9E",
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 0,
          "Department": "Marketing and Management",
          "created":1224043200000,
          "AppScope": "NO STAFF Linked"
      }, {
          "AppsName": "WinEdt",
          "AppDesc": "WinEdtis a software ASCII editor and shell for Microsoft Windows. It is primarily used for the creation of TeX (or LaTeX) documents, but can also be used to edit HTML or any other type of text file. ",
          "Appversion": 6,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "FACULTY SITE",
          "LicenseCount": 200,
          "LicenseUsed": 16,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "WinRats and Data",
          "AppDesc": "RATS (Regression Analysis of Time Series), a leading econometrics and time-series analysis software package.RATS is used worldwide by economists and others for analyzing time series and cross sectiona",
          "Appversion": 8.2,
          "AppDependency": "Packageing not Required,Run Off the Network",
          "AppOwner": "FACULTY",
          "LicenseType": "FACULTY SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "Economics",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "XSTAT Pro SPSPPM",
          "AppDesc": "",
          "Appversion": 10,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 3,
          "LicenseUsed": 3,
          "Department": "",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Adobe Indesign CS6",
          "AppDesc": "Adobe InDesign is a software application produced by Adobe Systems. It can be used to create works such as posters, flyers, brochures, magazines and books",
          "Appversion": 8,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 11,
          "LicenseUsed": 10,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Gretl",
          "AppDesc": "",
          "Appversion": "1.9.12",
          "AppDependency": "None",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "Economics",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "RStudio",
          "AppDesc": "",
          "Appversion": 0.97,
          "AppDependency": "R for Windows",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "TeXStudio",
          "AppDesc": "",
          "Appversion": "2.5.2",
          "AppDependency": "None",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "MikTex",
          "AppDesc": "",
          "Appversion": 2.9,
          "AppDependency": "None",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "Ghost Script",
          "AppDesc": "",
          "Appversion": 9.05,
          "AppDependency": "None",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "GS view",
          "AppDesc": "",
          "Appversion": 5,
          "AppDependency": "None",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "FlashPlayer",
          "AppDesc": "",
          "Appversion": 11.7,
          "AppDependency": "None",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "XLSTAT-Pro",
          "AppDesc": "",
          "Appversion": 2013,
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 1,
          "Department": "Marketing and Management",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "XLSTAT-3DPlot",
          "AppDesc": "",
          "Appversion": 2013,
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 1,
          "Department": "Marketing and Management",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "XLSTAT-PLS",
          "AppDesc": "",
          "Appversion": 2013,
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 1,
          "Department": "Marketing and Management",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "XLSTAT-PLSPM",
          "AppDesc": "",
          "Appversion": 2013,
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 1,
          "Department": "Marketing and Management",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "XLSTAT-CCR",
          "AppDesc": "",
          "Appversion": 2013,
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 1,
          "Department": "Marketing and Management",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "FirefoxESR",
          "AppDesc": "",
          "Appversion": "17.0.5",
          "AppDependency": "None",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "Chrome",
          "AppDesc": "",
          "Appversion": 27,
          "AppDependency": "N/A",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "Texnic Center",
          "AppDesc": "",
          "Appversion": 2.1,
          "AppDependency": "MikTeX",
          "AppOwner": "FREEWARE",
          "LicenseType": "FREEWARE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STUDENT"
      }, {
          "AppsName": "Eviews-8 -Network",
          "AppDesc": "",
          "Appversion": 8,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "FBE CONCURRENT",
          "LicenseCount": 200,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "BOTH"
      }, {
          "AppsName": "GAUSS",
          "AppDesc": "",
          "Appversion": 10,
          "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 0,
          "Department": "Economics",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Eviews 8 standalone",
          "AppDesc": "",
          "Appversion": 8,
           "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "MYOB AccountRight Premier",
          "AppDesc": "",
          "Appversion": "V19.9",
          "AppDependency": "n/a",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 3,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Vmware",
          "AppDesc": "",
          "Appversion": 10,
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 4,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "XLSTAT",
          "AppDesc": "",
          "Appversion": 2013,
           "AppDependency": "N/A",
          "AppOwner": "FACULTY",
          "LicenseType": "FACULTY SITE",
          "LicenseCount": 500,
          "LicenseUsed": 1,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Microsoft Project",
          "AppDesc": "",
          "Appversion": 2013,
          "AppDependency": "n/a",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 30,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "STATA",
          "AppDesc": "",
          "Appversion": 13,
          "AppDependency": "NIL",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 30,
          "LicenseUsed": 30,
          "Department": "Economics",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Articulate Storyline",
          "AppDesc": "",
          "Appversion": "N/a",
          "AppDependency": "N/a",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 1,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Dragon Naturally Speaking",
          "AppDesc": "",
          "Appversion": "N/a",
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 1,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Matlab",
          "AppDesc": "",
          "Appversion": "R2013b",
          "AppDependency": "VC++ 2005",
          "AppOwner": "UNI",
          "LicenseType": "UNI SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "GAUSS",
          "AppDesc": "",
          "Appversion": 14,
          "AppDependency": "nil",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 3,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Foresight",
          "AppDesc": "",
          "Appversion": 1,
          "AppDependency": "NO",
          "AppOwner": "FACULTY",
          "LicenseType": "UNI SITE",
          "LicenseCount": 0,
          "LicenseUsed": 0,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
      }, {
          "AppsName": "Microsoft Visio Pro 2013",
          "AppDesc": "",
          "Appversion": "Pro 2013",
          "AppDependency": "",
          "AppOwner": "FACULTY",
          "LicenseType": "INDIVIDUAL",
          "LicenseCount": 30,
          "LicenseUsed": 24,
          "Department": "General",
          "created":1224043200000,
          "AppScope": "STAFF"
      });
  });